apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nabu-api.fullname" . }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "nabu-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nabu-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nabu-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
              containerPort: 80
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  {{- with .Values.server.dbSecret }}
                  name: {{ .name }}
                  key: {{ .key }}
                  {{- end }}
