apiVersion: v1
kind: Service
metadata:
  name: {{ include "nabu-api.fullname" . }}
  labels:
    {{- include "nabu-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "nabu-api.selectorLabels" . | nindent 4 }}
