"""add logs schema and api table

Revision ID: 894e644e2092
Revises: 989e4aa162c7
Create Date: 2022-04-06 13:25:36.056866

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '894e644e2092'
down_revision = '989e4aa162c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA logs')
    op.create_table('api',
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp'),
    schema='logs'
    )
    op.create_index(op.f('ix_logs_api_client_id'), 'api', ['client_id'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_api_referer'), 'api', ['referer'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_api_response_count'), 'api', ['response_count'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_api_status_code'), 'api', ['status_code'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_api_timestamp'), 'api', ['timestamp'], unique=False, schema='logs')
    op.drop_index('ix_articleclusterkeyword_term', table_name='articleclusterkeyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articleclusterkeyword_term', 'articleclusterkeyword', ['term'], unique=False)
    op.drop_index(op.f('ix_logs_api_timestamp'), table_name='api', schema='logs')
    op.drop_index(op.f('ix_logs_api_status_code'), table_name='api', schema='logs')
    op.drop_index(op.f('ix_logs_api_response_count'), table_name='api', schema='logs')
    op.drop_index(op.f('ix_logs_api_referer'), table_name='api', schema='logs')
    op.drop_index(op.f('ix_logs_api_client_id'), table_name='api', schema='logs')
    op.drop_table('api', schema='logs')
    op.execute('DROP SCHEMA logs')
    # ### end Alembic commands ###
