name: ETL CD
on:
  push:
    branches:
      - main
    paths:
      - 'etl/**'
      - '.github/workflows/etl_cd.yaml'
jobs:
  build-push-image:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Build container image
      run: cd etl && docker build -t registry.digitalocean.com/ptb/etl:$(echo $GITHUB_SHA | head -c7) -t registry.digitalocean.com/ptb/etl:latest .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/ptb/etl --all-tags
