name: ETL CI
on:
  pull_request:
    branches:
      - main
    paths:
      - 'etl/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
#    commented out, but here for when we add integration tests and need a DB to interact with
#    services:
#      # Label used to access the service container
#      postgres:
#        # Docker Hub image
#        image: postgres
#        # Provide the password for postgres
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: postgres
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          # Maps tcp port 5432 on service container to the host
#          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8
    - name: Install dependencies
      run: cd etl && poetry config virtualenvs.create false && poetry install --no-interaction
    - name: Install spacy package
      run: python -m spacy download en_core_web_sm
    - name: run tests
      run: pytest etl/tests