name: Pulumi preview
on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infra_preview.yaml'
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: cd infrastructure/etl && pip install -r requirements.txt
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: prod
          work-dir: infrastructure/etl
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}