name: PTBModels CD
on:
  push:
    branches:
      - main
    paths:
      - 'ptbmodels/pyproject.toml'
jobs:
  build-publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8
    - name: Publish package
      run: cd ptbmodels && poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
